# Generated by Django 4.1.7 on 2024-02-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_filmwork_persons_alter_genrefilmwork_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.CharField(max_length=100, verbose_name='role'),
        ),
    ]
