"""change_social_account

Revision ID: 1875654d2248
Revises: 65a4e8f17754
Create Date: 2024-05-09 04:01:19.629117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.postgres_db import Base


# revision identifiers, used by Alembic.
revision: str = '1875654d2248'
down_revision: Union[str, None] = '65a4e8f17754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_account', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_account', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
