"""add_user_role

Revision ID: 253a99264a77
Revises: 5f5b6d1036ec
Create Date: 2024-04-24 02:16:08.325969

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "253a99264a77"
down_revision: Union[str, None] = "5f5b6d1036ec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "authentication", ["id"])
    op.create_unique_constraint(None, "users", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_constraint(None, "authentication", type_="unique")
    # ### end Alembic commands ###
