"""fix_user_model

Revision ID: b9e284d66a5a
Revises: 253a99264a77
Create Date: 2024-04-25 01:10:11.289237

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9e284d66a5a"
down_revision: Union[str, None] = "253a99264a77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "login",
        new_column_name="email",
        type_=sa.String(length=255),
        nullable=False,
    )
    op.drop_constraint("users_login_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        new_column_name="login",
        type_=sa.String(length=255),
        nullable=False,
    )
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_login_key", "users", ["login"])
    # ### end Alembic commands ###
